blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/$', views.index),
    url(r'^article/(?P<article_id>[0-9]+)$', views.article_page,name='article_page'),
    url(r'^edit/(?P<article_id>[0-9]+)$',views.edit_page,name='edit_page'),
    url(r'^edit/action$',views.edit_action,name='edit_action'),
    url(r'^update/(?P<article_id>[0-9]+)$',views.update,name='update_page'),
    url(r'^update/action/(?P<article_id>[0-9]+)$',views.update_action,name='update_action'),
]

myblog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls',namespace='blog')),

]

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Artical(models.Model):
    title = models.CharField(max_length=32,default='Title')
    content = models.TextField(null=True)

    def __unicode__(self):
        return self.title

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponseRedirect
from django.shortcuts import render
from . import models

# Create your views here.
def index(request):
    articles = models.Artical.objects.all
    return render(request, 'blog/index.html',{'articles' : articles})

def article_page(request,article_id):
    article = models.Artical.objects.get(pk = article_id)
    return render(request,'blog/article_page.html',{'article':article})

def edit_page(request,article_id):
    if str(article_id) == '0':
        return render(request,'blog/edit_page.html')
    article = models.Artical.objects.get(pk = article_id)
    return render(request,'blog/edit_page.html',{'article':article})

def edit_action(request):
    title = request.POST.get('Title','TITLE')
    content = request.POST.get('Content','CONTENT')
    id = request.POST.get('article_id','null')
    if(str(id) == 0):
        models.Artical.objects.create(title=title,content=content)
        return HttpResponseRedirect('/blog/index')
    else:
        article = models.Artical.objects.get(pk = id)
        article.title = title
        article.content = content
        article.save()
        return render(request,'blog/article_page.html',{'article':article})


def update(request,article_id):
    article = models.Artical.objects.get(pk=article_id)
    return render(request,'blog/update.html',{'article': article})

def update_action(request,article_id):
    title = request.POST.get('Title', 'TITLE')
    content = request.POST.get('Content', 'CONTENT')
    models.Artical.objects.filter(pk=article_id).update(content = content)
    models.Artical.objects.filter(pk=article_id).update(title=title)
    return HttpResponseRedirect('/blog/index')

blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Article Page</title>
</head>
<body>
<h1>{{ article.title }}</h1>
<br/>
<h3>{{ article.content }}</h3>
<br/>
<br/>
<a href="{% url 'blog:edit_page' article.id %}">Update Article</a>
</body>
</html>

blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New</title>
</head>
<body>
<form action="{% url 'blog:edit_action' %}" method="post">
    {% csrf_token %}
    {% if article %}
        <input type="hidden" name="article_id" value="{{ article.id }}">
        <label> Article's name
            <input type="text" name="Title" value="{{ article.title }}">
        </label>
        <br/>
        <label> Article's content
            <input type="text" name="Content" value="{{ article.content }}">
        </label>
        <br/>
    {% else %}
        <input type="hidden" name="article_id" value="0">
        <label> Article's name
            <input type="text" name="Title">
        </label>
        <br/>
        <label> Article's content
            <input type="text" name="Content">
        </label>
        <br/>
    {% endif %}
    <input type="submit" value="Submit">

</form>
</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1><a href="{% url 'blog:edit_page' 0 %}">New Article</a></h1>

{% for article in articles %}
    <a href = "{% url 'blog:article_page' article.id %}">{{ article.title }}</a>
        <br/>
{% endfor %}
</body>
</html>

blog/templates/blog/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>update</title>
</head>
<body>
<form action="{% url 'blog:update_action' article.id%}" method="post">
    {% csrf_token %}
    <label> Article's name
    <input type="text"name="Title">
    </label>
        <br/>
    <label> Article's content
    <input type="text"name="Content">
    </label>
        <br/>
    <input type="submit" value="Submit">
</form>
</body>
</html>